spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/archiver_dev?socketTimeout=90
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


    hikari:
      connection-timeout: 50000
      maximum-pool-size: 400
      minimum-idle: 5


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect


    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
